---

version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: '04:00'
    timezone: "Europe/London"
  versioning-strategy: lockfile-only
  rebase-strategy: 'off'
